### ISSUE TITLE
Why not melpa?

### ISSUE THREAD

**Issue by slegetank** [CodyReichert/es6-snippets#2]
We need it on melpa

**Comment by CodyReichert** [comment]
Just sent a PR to get it added! https://github.com/melpa/melpa/pull/5603

**Comment by CodyReichert** [comment]
@slegetank - just fyi it wasn't added for some reason: https://github.com/melpa/melpa/pull/5603

I'll keep up and see if we can make this available on melpa somehow.

For now just let me know if I can make the install easier in any way. Thanks again!
